// Generated by CoffeeScript 1.6.3
(function() {
  Backbone.ComputedAttributes = {
    compute: function(computed_attribute, options, fn) {
      var clone, model;
      if (!fn) {
        fn = options;
        options = {};
      }
      model = this;
      clone = Object.create(this);
      clone.get = function(attribute) {
        model.on('change:' + attribute, function() {
          return model.set(computed_attribute, fn.apply(this));
        });
        return model.get(attribute);
      };
      return model.set(computed_attribute, fn.apply(clone));
    }
  };

  Backbone.Model.prototype.compute = Backbone.ComputedAttributes.compute;

}).call(this);
